import path from "node:path";
const __dirname = import.meta.dirname;

/**
 * Constructs and returns an absolute file path by resolving a given relative path
 * against the current directory of the module.
 *
 * @param {string} relativePath - The relative file path to be resolved.
 * @return {string} The absolute file path generated by combining the current directory and the relative path.
 */
export function getFilePath(relativePath) {
    return path.join(__dirname, relativePath);
}
